from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Pokemon:
    regional: int
    national: int
    name: str
    family: tuple[str, ...]
    method: str
    black_only: bool = False
    white_only: bool = False
    event_only: bool = False


# Pokémon Black/White regional dex. Victini is #000; Snivy starts at #001.
# Keep this boring and explicit. Clever generated dex data is how gremlins hatch.
UNOVA_DEX: tuple[Pokemon, ...] = (
    Pokemon(0, 494, "Victini", ("Victini",), "event", event_only=True),
    Pokemon(1, 495, "Snivy", ("Snivy", "Servine", "Serperior"), "starter/breed/trade"),
    Pokemon(2, 496, "Servine", ("Snivy", "Servine", "Serperior"), "evolve Snivy"),
    Pokemon(3, 497, "Serperior", ("Snivy", "Servine", "Serperior"), "evolve Servine"),
    Pokemon(4, 498, "Tepig", ("Tepig", "Pignite", "Emboar"), "starter/breed/trade"),
    Pokemon(5, 499, "Pignite", ("Tepig", "Pignite", "Emboar"), "evolve Tepig"),
    Pokemon(6, 500, "Emboar", ("Tepig", "Pignite", "Emboar"), "evolve Pignite"),
    Pokemon(7, 501, "Oshawott", ("Oshawott", "Dewott", "Samurott"), "starter/breed/trade"),
    Pokemon(8, 502, "Dewott", ("Oshawott", "Dewott", "Samurott"), "evolve Oshawott"),
    Pokemon(9, 503, "Samurott", ("Oshawott", "Dewott", "Samurott"), "evolve Dewott"),
    Pokemon(10, 504, "Patrat", ("Patrat", "Watchog"), "catch"),
    Pokemon(11, 505, "Watchog", ("Patrat", "Watchog"), "catch/evolve Patrat"),
    Pokemon(12, 506, "Lillipup", ("Lillipup", "Herdier", "Stoutland"), "catch"),
    Pokemon(13, 507, "Herdier", ("Lillipup", "Herdier", "Stoutland"), "catch/evolve Lillipup"),
    Pokemon(14, 508, "Stoutland", ("Lillipup", "Herdier", "Stoutland"), "evolve Herdier"),
    Pokemon(15, 509, "Purrloin", ("Purrloin", "Liepard"), "catch"),
    Pokemon(16, 510, "Liepard", ("Purrloin", "Liepard"), "catch/evolve Purrloin"),
    Pokemon(17, 511, "Pansage", ("Pansage", "Simisage"), "gift/catch/trade"),
    Pokemon(18, 512, "Simisage", ("Pansage", "Simisage"), "use Leaf Stone on Pansage"),
    Pokemon(19, 513, "Pansear", ("Pansear", "Simisear"), "gift/catch/trade"),
    Pokemon(20, 514, "Simisear", ("Pansear", "Simisear"), "use Fire Stone on Pansear"),
    Pokemon(21, 515, "Panpour", ("Panpour", "Simipour"), "gift/catch/trade"),
    Pokemon(22, 516, "Simipour", ("Panpour", "Simipour"), "use Water Stone on Panpour"),
    Pokemon(23, 517, "Munna", ("Munna", "Musharna"), "catch"),
    Pokemon(24, 518, "Musharna", ("Munna", "Musharna"), "catch/use Moon Stone on Munna"),
    Pokemon(25, 519, "Pidove", ("Pidove", "Tranquill", "Unfezant"), "catch"),
    Pokemon(26, 520, "Tranquill", ("Pidove", "Tranquill", "Unfezant"), "catch/evolve Pidove"),
    Pokemon(27, 521, "Unfezant", ("Pidove", "Tranquill", "Unfezant"), "evolve Tranquill"),
    Pokemon(28, 522, "Blitzle", ("Blitzle", "Zebstrika"), "catch"),
    Pokemon(29, 523, "Zebstrika", ("Blitzle", "Zebstrika"), "catch/evolve Blitzle"),
    Pokemon(30, 524, "Roggenrola", ("Roggenrola", "Boldore", "Gigalith"), "catch"),
    Pokemon(31, 525, "Boldore", ("Roggenrola", "Boldore", "Gigalith"), "catch/evolve Roggenrola"),
    Pokemon(32, 526, "Gigalith", ("Roggenrola", "Boldore", "Gigalith"), "trade evolve Boldore"),
    Pokemon(33, 527, "Woobat", ("Woobat", "Swoobat"), "catch"),
    Pokemon(34, 528, "Swoobat", ("Woobat", "Swoobat"), "friendship evolve Woobat"),
    Pokemon(35, 529, "Drilbur", ("Drilbur", "Excadrill"), "catch"),
    Pokemon(36, 530, "Excadrill", ("Drilbur", "Excadrill"), "catch/evolve Drilbur"),
    Pokemon(37, 531, "Audino", ("Audino",), "catch shaking grass"),
    Pokemon(38, 532, "Timburr", ("Timburr", "Gurdurr", "Conkeldurr"), "catch"),
    Pokemon(39, 533, "Gurdurr", ("Timburr", "Gurdurr", "Conkeldurr"), "catch/evolve Timburr"),
    Pokemon(40, 534, "Conkeldurr", ("Timburr", "Gurdurr", "Conkeldurr"), "trade evolve Gurdurr"),
    Pokemon(41, 535, "Tympole", ("Tympole", "Palpitoad", "Seismitoad"), "catch"),
    Pokemon(42, 536, "Palpitoad", ("Tympole", "Palpitoad", "Seismitoad"), "catch/evolve Tympole"),
    Pokemon(43, 537, "Seismitoad", ("Tympole", "Palpitoad", "Seismitoad"), "evolve Palpitoad"),
    Pokemon(44, 538, "Throh", ("Throh",), "catch/trade", white_only=True),
    Pokemon(45, 539, "Sawk", ("Sawk",), "catch/trade", black_only=True),
    Pokemon(46, 540, "Sewaddle", ("Sewaddle", "Swadloon", "Leavanny"), "catch"),
    Pokemon(47, 541, "Swadloon", ("Sewaddle", "Swadloon", "Leavanny"), "catch/evolve Sewaddle"),
    Pokemon(48, 542, "Leavanny", ("Sewaddle", "Swadloon", "Leavanny"), "friendship evolve Swadloon"),
    Pokemon(49, 543, "Venipede", ("Venipede", "Whirlipede", "Scolipede"), "catch"),
    Pokemon(50, 544, "Whirlipede", ("Venipede", "Whirlipede", "Scolipede"), "catch/evolve Venipede"),
    Pokemon(51, 545, "Scolipede", ("Venipede", "Whirlipede", "Scolipede"), "evolve Whirlipede"),
    Pokemon(52, 546, "Cottonee", ("Cottonee", "Whimsicott"), "catch/trade", black_only=True),
    Pokemon(53, 547, "Whimsicott", ("Cottonee", "Whimsicott"), "use Sun Stone on Cottonee", black_only=True),
    Pokemon(54, 548, "Petilil", ("Petilil", "Lilligant"), "catch/trade", white_only=True),
    Pokemon(55, 549, "Lilligant", ("Petilil", "Lilligant"), "use Sun Stone on Petilil", white_only=True),
    Pokemon(56, 550, "Basculin", ("Basculin",), "fish/surf/catch"),
    Pokemon(57, 551, "Sandile", ("Sandile", "Krokorok", "Krookodile"), "catch"),
    Pokemon(58, 552, "Krokorok", ("Sandile", "Krokorok", "Krookodile"), "catch/evolve Sandile"),
    Pokemon(59, 553, "Krookodile", ("Sandile", "Krokorok", "Krookodile"), "evolve Krokorok"),
    Pokemon(60, 554, "Darumaka", ("Darumaka", "Darmanitan"), "catch"),
    Pokemon(61, 555, "Darmanitan", ("Darumaka", "Darmanitan"), "catch/evolve Darumaka"),
    Pokemon(62, 556, "Maractus", ("Maractus",), "catch"),
    Pokemon(63, 557, "Dwebble", ("Dwebble", "Crustle"), "catch"),
    Pokemon(64, 558, "Crustle", ("Dwebble", "Crustle"), "catch/evolve Dwebble"),
    Pokemon(65, 559, "Scraggy", ("Scraggy", "Scrafty"), "catch"),
    Pokemon(66, 560, "Scrafty", ("Scraggy", "Scrafty"), "evolve Scraggy"),
    Pokemon(67, 561, "Sigilyph", ("Sigilyph",), "catch"),
    Pokemon(68, 562, "Yamask", ("Yamask", "Cofagrigus"), "catch"),
    Pokemon(69, 563, "Cofagrigus", ("Yamask", "Cofagrigus"), "evolve Yamask"),
    Pokemon(70, 564, "Tirtouga", ("Tirtouga", "Carracosta"), "fossil choice/trade"),
    Pokemon(71, 565, "Carracosta", ("Tirtouga", "Carracosta"), "evolve Tirtouga"),
    Pokemon(72, 566, "Archen", ("Archen", "Archeops"), "fossil choice/trade"),
    Pokemon(73, 567, "Archeops", ("Archen", "Archeops"), "evolve Archen"),
    Pokemon(74, 568, "Trubbish", ("Trubbish", "Garbodor"), "catch"),
    Pokemon(75, 569, "Garbodor", ("Trubbish", "Garbodor"), "catch/evolve Trubbish"),
    Pokemon(76, 570, "Zorua", ("Zorua", "Zoroark"), "event/transfer setup"),
    Pokemon(77, 571, "Zoroark", ("Zorua", "Zoroark"), "event/transfer setup/evolve Zorua"),
    Pokemon(78, 572, "Minccino", ("Minccino", "Cinccino"), "catch"),
    Pokemon(79, 573, "Cinccino", ("Minccino", "Cinccino"), "use Shiny Stone on Minccino"),
    Pokemon(80, 574, "Gothita", ("Gothita", "Gothorita", "Gothitelle"), "catch/trade", black_only=True),
    Pokemon(81, 575, "Gothorita", ("Gothita", "Gothorita", "Gothitelle"), "catch/evolve Gothita", black_only=True),
    Pokemon(82, 576, "Gothitelle", ("Gothita", "Gothorita", "Gothitelle"), "evolve Gothorita", black_only=True),
    Pokemon(83, 577, "Solosis", ("Solosis", "Duosion", "Reuniclus"), "catch/trade", white_only=True),
    Pokemon(84, 578, "Duosion", ("Solosis", "Duosion", "Reuniclus"), "catch/evolve Solosis", white_only=True),
    Pokemon(85, 579, "Reuniclus", ("Solosis", "Duosion", "Reuniclus"), "evolve Duosion", white_only=True),
    Pokemon(86, 580, "Ducklett", ("Ducklett", "Swanna"), "catch"),
    Pokemon(87, 581, "Swanna", ("Ducklett", "Swanna"), "catch/evolve Ducklett"),
    Pokemon(88, 582, "Vanillite", ("Vanillite", "Vanillish", "Vanilluxe"), "catch"),
    Pokemon(89, 583, "Vanillish", ("Vanillite", "Vanillish", "Vanilluxe"), "catch/evolve Vanillite"),
    Pokemon(90, 584, "Vanilluxe", ("Vanillite", "Vanillish", "Vanilluxe"), "evolve Vanillish"),
    Pokemon(91, 585, "Deerling", ("Deerling", "Sawsbuck"), "catch"),
    Pokemon(92, 586, "Sawsbuck", ("Deerling", "Sawsbuck"), "evolve Deerling"),
    Pokemon(93, 587, "Emolga", ("Emolga",), "catch shaking grass"),
    Pokemon(94, 588, "Karrablast", ("Karrablast", "Escavalier"), "catch"),
    Pokemon(95, 589, "Escavalier", ("Karrablast", "Escavalier"), "trade Karrablast for Shelmet"),
    Pokemon(96, 590, "Foongus", ("Foongus", "Amoonguss"), "catch"),
    Pokemon(97, 591, "Amoonguss", ("Foongus", "Amoonguss"), "catch/evolve Foongus"),
    Pokemon(98, 592, "Frillish", ("Frillish", "Jellicent"), "surf/catch"),
    Pokemon(99, 593, "Jellicent", ("Frillish", "Jellicent"), "catch/evolve Frillish"),
    Pokemon(100, 594, "Alomomola", ("Alomomola",), "surf rippling water"),
    Pokemon(101, 595, "Joltik", ("Joltik", "Galvantula"), "catch"),
    Pokemon(102, 596, "Galvantula", ("Joltik", "Galvantula"), "evolve Joltik"),
    Pokemon(103, 597, "Ferroseed", ("Ferroseed", "Ferrothorn"), "catch"),
    Pokemon(104, 598, "Ferrothorn", ("Ferroseed", "Ferrothorn"), "evolve Ferroseed"),
    Pokemon(105, 599, "Klink", ("Klink", "Klang", "Klinklang"), "catch"),
    Pokemon(106, 600, "Klang", ("Klink", "Klang", "Klinklang"), "catch/evolve Klink"),
    Pokemon(107, 601, "Klinklang", ("Klink", "Klang", "Klinklang"), "evolve Klang"),
    Pokemon(108, 602, "Tynamo", ("Tynamo", "Eelektrik", "Eelektross"), "catch"),
    Pokemon(109, 603, "Eelektrik", ("Tynamo", "Eelektrik", "Eelektross"), "evolve Tynamo"),
    Pokemon(110, 604, "Eelektross", ("Tynamo", "Eelektrik", "Eelektross"), "use Thunder Stone on Eelektrik"),
    Pokemon(111, 605, "Elgyem", ("Elgyem", "Beheeyem"), "catch"),
    Pokemon(112, 606, "Beheeyem", ("Elgyem", "Beheeyem"), "evolve Elgyem"),
    Pokemon(113, 607, "Litwick", ("Litwick", "Lampent", "Chandelure"), "catch"),
    Pokemon(114, 608, "Lampent", ("Litwick", "Lampent", "Chandelure"), "catch/evolve Litwick"),
    Pokemon(115, 609, "Chandelure", ("Litwick", "Lampent", "Chandelure"), "use Dusk Stone on Lampent"),
    Pokemon(116, 610, "Axew", ("Axew", "Fraxure", "Haxorus"), "catch"),
    Pokemon(117, 611, "Fraxure", ("Axew", "Fraxure", "Haxorus"), "catch/evolve Axew"),
    Pokemon(118, 612, "Haxorus", ("Axew", "Fraxure", "Haxorus"), "evolve Fraxure"),
    Pokemon(119, 613, "Cubchoo", ("Cubchoo", "Beartic"), "catch"),
    Pokemon(120, 614, "Beartic", ("Cubchoo", "Beartic"), "catch/evolve Cubchoo"),
    Pokemon(121, 615, "Cryogonal", ("Cryogonal",), "catch"),
    Pokemon(122, 616, "Shelmet", ("Shelmet", "Accelgor"), "catch"),
    Pokemon(123, 617, "Accelgor", ("Shelmet", "Accelgor"), "trade Shelmet for Karrablast"),
    Pokemon(124, 618, "Stunfisk", ("Stunfisk",), "catch"),
    Pokemon(125, 619, "Mienfoo", ("Mienfoo", "Mienshao"), "catch"),
    Pokemon(126, 620, "Mienshao", ("Mienfoo", "Mienshao"), "evolve Mienfoo"),
    Pokemon(127, 621, "Druddigon", ("Druddigon",), "catch"),
    Pokemon(128, 622, "Golett", ("Golett", "Golurk"), "catch"),
    Pokemon(129, 623, "Golurk", ("Golett", "Golurk"), "evolve Golett"),
    Pokemon(130, 624, "Pawniard", ("Pawniard", "Bisharp"), "catch"),
    Pokemon(131, 625, "Bisharp", ("Pawniard", "Bisharp"), "catch/evolve Pawniard"),
    Pokemon(132, 626, "Bouffalant", ("Bouffalant",), "catch"),
    Pokemon(133, 627, "Rufflet", ("Rufflet", "Braviary"), "catch/trade", white_only=True),
    Pokemon(134, 628, "Braviary", ("Rufflet", "Braviary"), "evolve Rufflet", white_only=True),
    Pokemon(135, 629, "Vullaby", ("Vullaby", "Mandibuzz"), "catch/trade", black_only=True),
    Pokemon(136, 630, "Mandibuzz", ("Vullaby", "Mandibuzz"), "evolve Vullaby", black_only=True),
    Pokemon(137, 631, "Heatmor", ("Heatmor",), "catch"),
    Pokemon(138, 632, "Durant", ("Durant",), "catch"),
    Pokemon(139, 633, "Deino", ("Deino", "Zweilous", "Hydreigon"), "catch", black_only=True),
    Pokemon(140, 634, "Zweilous", ("Deino", "Zweilous", "Hydreigon"), "evolve Deino", black_only=True),
    Pokemon(141, 635, "Hydreigon", ("Deino", "Zweilous", "Hydreigon"), "evolve Zweilous", black_only=True),
    Pokemon(142, 636, "Larvesta", ("Larvesta", "Volcarona"), "egg/catch"),
    Pokemon(143, 637, "Volcarona", ("Larvesta", "Volcarona"), "catch static/evolve Larvesta"),
    Pokemon(144, 638, "Cobalion", ("Cobalion",), "legendary catch"),
    Pokemon(145, 639, "Terrakion", ("Terrakion",), "legendary catch"),
    Pokemon(146, 640, "Virizion", ("Virizion",), "legendary catch"),
    Pokemon(147, 641, "Tornadus", ("Tornadus",), "roamer/trade", black_only=True),
    Pokemon(148, 642, "Thundurus", ("Thundurus",), "roamer/trade", white_only=True),
    Pokemon(149, 643, "Reshiram", ("Reshiram",), "story legendary/trade", black_only=True),
    Pokemon(150, 644, "Zekrom", ("Zekrom",), "story legendary/trade", white_only=True),
    Pokemon(151, 645, "Landorus", ("Landorus",), "requires Tornadus + Thundurus"),
    Pokemon(152, 646, "Kyurem", ("Kyurem",), "legendary catch"),
    Pokemon(153, 647, "Keldeo", ("Keldeo",), "event", event_only=True),
    Pokemon(154, 648, "Meloetta", ("Meloetta",), "event", event_only=True),
    Pokemon(155, 649, "Genesect", ("Genesect",), "event", event_only=True),
)

BY_NAME = {pokemon.name.casefold(): pokemon for pokemon in UNOVA_DEX}
BY_REGIONAL = {pokemon.regional: pokemon for pokemon in UNOVA_DEX}
BY_NATIONAL = {pokemon.national: pokemon for pokemon in UNOVA_DEX}
