from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path

import typer
from rich.console import Console

from pokedex_completer_gen5.agents.planner import plan_next_tasks
from pokedex_completer_gen5.agents.providers.factory import create_planner_provider
from pokedex_completer_gen5.ai.benchmark import dry_run_model_routing
from pokedex_completer_gen5.ai.orchestrator import OrchestrationRequest, orchestrate, orchestrator_capabilities
from pokedex_completer_gen5.ai.router import router_payload
from pokedex_completer_gen5.autonomy.loop import AutonomyBudget, AutonomyConfig, run_autonomy
from pokedex_completer_gen5.backend.report_store import sha256_file, store_dex_report
from pokedex_completer_gen5.dex.catchable_targets import build_catchable_inventory_report
from pokedex_completer_gen5.dex.pc_living_dex import build_pc_living_dex_report
from pokedex_completer_gen5.integrations.env import load_environment
from pokedex_completer_gen5.integrations.provider_health import provider_health_payload
from pokedex_completer_gen5.persistence.database import init_database
from pokedex_completer_gen5.saveio.gen5_save import build_save_output, build_save_payload, write_save_report
from pokedex_completer_gen5.trajectory import read_jsonl_events

app = typer.Typer(help="Generation 5 physical inventory and catchable-target completer.")
console = Console()
load_environment()
if os.name == "nt":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())


@app.command()
def version() -> None:
    """Print package version."""
    from pokedex_completer_gen5 import __version__

    console.print(f"pokedex-completer-gen5 {__version__}")


@app.command("inspect-save")
def inspect_save(
    save_path: Path = typer.Argument(..., help="Path to Gen 5 save file."),
    game: str = typer.Option("white", help="black, white, black2, or white2."),
    copy: str = typer.Option("auto", help="auto, 0, or 1."),
) -> None:
    """Read a Gen 5 save and print physical party/PC extraction plus planner status."""
    console.print(build_save_output(save_path, game, copy, "markdown"))


@app.command("pc-living-dex")
def pc_living_dex(
    save_path: Path = typer.Argument(..., help="Path to Gen 5 save file."),
    game: str = typer.Option("white", help="black, white, black2, or white2."),
    copy: str = typer.Option("auto", help="auto, 0, or 1."),
    scope: str = typer.Option("regional", help="regional now; national later."),
    include_party: bool = typer.Option(True, help="Count party as currently owned alongside PC."),
    target_policy: str = typer.Option("game-regional", help="game-regional, all-regional, or catchable-only."),
) -> None:
    """Compare PC/party physical bodies against the regional PC Living Dex target."""
    payload = build_save_payload(save_path, game, copy)
    report = build_pc_living_dex_report(
        payload,
        game,
        scope=scope,
        include_party=include_party,
        target_policy=target_policy,
    )
    console.print_json(data=report.to_dict())


@app.command("catchable-report")
def catchable_report(
    save_path: Path = typer.Argument(..., help="Path to Gen 5 save file."),
    game: str = typer.Option("white", help="black, white, black2, or white2."),
    copy: str = typer.Option("auto", help="auto, 0, or 1."),
    mode: str = typer.Option("direct", help="direct or obtainable."),
) -> None:
    """Compare active PC/party bodies against catchable targets for this game."""
    payload = build_save_payload(save_path, game, copy)
    report = build_catchable_inventory_report(payload, game, mode=mode)
    console.print_json(data=report.to_dict())


@app.command("report-living-dex")
def report_living_dex(
    save_path: Path = typer.Argument(..., help="Path to Gen 5 save file."),
    game: str = typer.Option("white", help="black, white, black2, or white2."),
    copy: str = typer.Option("auto", help="auto, 0, or 1."),
    output: Path | None = typer.Option(None, help="Optional report output path."),
    format: str = typer.Option("markdown", help="markdown or json."),
) -> None:
    """Generate a read-only Living Dex report from a Gen 5 save file."""
    output_path, report = write_save_report(save_path, game, copy, output, format)
    console.print(report)
    console.print(f"[green]Report written to:[/green] {output_path}")


@app.command("plan-report")
def plan_report(
    report_path: Path = typer.Argument(..., help="Path to a JSON report generated by report-living-dex."),
    provider: str = typer.Option("openai", help="openai, anthropic, or google."),
    model: str | None = typer.Option(None, help="Optional provider-specific model override."),
) -> None:
    """Ask an LLM provider for prioritized next tasks from a report JSON file."""
    payload = json.loads(report_path.read_text(encoding="utf-8"))
    planner_provider = create_planner_provider(provider, model=model)
    result = plan_next_tasks(payload, planner_provider)
    console.print_json(data=result.to_dict())


@app.command("sync-report")
def sync_report(
    save_path: Path = typer.Argument(..., help="Path to Gen 5 save file."),
    game: str = typer.Option("white", help="black, white, black2, or white2."),
    copy: str = typer.Option("auto", help="auto, 0, or 1."),
) -> None:
    """Generate a report payload and store sanitized metadata in Supabase."""
    payload = build_save_payload(save_path, game, copy)
    response = store_dex_report(payload, save_sha256=sha256_file(save_path))
    console.print("[green]Synced sanitized dex report to Supabase.[/green]")
    console.print(response)


@app.command("provider-health")
def provider_health() -> None:
    """Show which external provider environment variables are configured."""
    console.print_json(data=provider_health_payload())


@app.command("init-db")
def init_db() -> None:
    """Create the local SQLite runtime database tables."""
    init_database()
    console.print("[green]Local SQLite runtime database is ready.[/green]")


@app.command("trajectory")
def trajectory(limit: int = typer.Option(100, help="Number of recent JSONL events to print.")) -> None:
    """Print recent local JSONL trajectory events."""
    console.print_json(data={"events": read_jsonl_events(limit=limit)})


@app.command("autonomous-run")
def autonomous_run(
    save_path: Path | None = typer.Option(None, help="Optional Gen 5 save path for Living Dex observation."),
    game: str = typer.Option("white", help="black, white, black2, or white2."),
    max_iterations: int = typer.Option(1, help="Maximum supervisor iterations."),
    max_seconds: int = typer.Option(60, help="Wall-clock runtime budget."),
    token_budget: int = typer.Option(0, help="Advisory LLM token budget; 0 means no LLM calls."),
    execute: bool = typer.Option(False, help="Allow non-dry-run actions once action adapters exist."),
) -> None:
    """Run the durable autonomy supervisor scaffold."""
    result = run_autonomy(
        AutonomyConfig(
            game=game,
            save_path=save_path,
            dry_run=not execute,
            budget=AutonomyBudget(
                max_iterations=max_iterations,
                max_seconds=max_seconds,
                token_budget=token_budget,
            ),
        )
    )
    console.print_json(data=result.to_dict())


@app.command("model-router")
def model_router() -> None:
    """Print current cost-aware model routing configuration."""
    console.print_json(data=router_payload())


@app.command("benchmark-routing")
def benchmark_routing(
    cases_dir: Path = typer.Option(Path("tests/planner_cases"), help="Directory of benchmark case JSON files."),
) -> None:
    """Dry-run benchmark cases through the model router without calling any provider."""
    console.print_json(data={"cases": dry_run_model_routing(cases_dir)})


@app.command("orchestrator-info")
def orchestrator_info() -> None:
    """Show configured LLM orchestration modes and providers without spending tokens."""
    console.print_json(data=orchestrator_capabilities())


@app.command("orchestrate")
def orchestrate_prompt(
    prompt: str = typer.Argument(..., help="Prompt for the advisory LLM orchestrator."),
    mode: str = typer.Option("route", help="single, route, ensemble, or review."),
    provider: str | None = typer.Option(None, help="Optional openai, anthropic, google, or compatible override."),
    model: str | None = typer.Option(None, help="Optional model override."),
    max_providers: int = typer.Option(3, min=1, max=3, help="Maximum ensemble providers."),
) -> None:
    """Run one routed or multi-provider advisory request. This can spend API money."""
    result = orchestrate(
        OrchestrationRequest(
            prompt=prompt,
            mode=mode,  # type: ignore[arg-type]
            provider=provider,  # type: ignore[arg-type]
            model=model,
            max_providers=max_providers,
        )
    )
    console.print_json(data=result.to_dict())


@app.command()
def serve(
    host: str = typer.Option("127.0.0.1", help="REST API bind host."),
    port: int = typer.Option(8787, help="REST API bind port."),
) -> None:
    """Run the local REST API skeleton."""
    import uvicorn

    uvicorn.run("pokedex_completer_gen5.server.rest:app", host=host, port=port, reload=False)


if __name__ == "__main__":
    app()
